version: '3.0'
volumes:
  database:
services:
  kafka-lag-exporter:
    image: lightbend/kafka-lag-exporter:0.5.5
    container_name: kafka-lag-exporter
    hostname: kafka-lag-exporter
    restart: always
    volumes:
      - $MONITORING_STACK/assets/prometheus/kafka-lag-exporter:/opt/docker/conf
      - $MONITORING_STACK/assets/prometheus/security:/etc/kafka/secrets