version: '3.0'
volumes:
  database:
services:
  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana/provisioning/:/etc/grafana/provisioning/
